version: '3'
networks:
      pim:
services:
  pim-web:
    image: jksusu/pim-web:0.01
    container_name: pim-web-dev
    privileged: true
    ports:
      - "80:80"
    restart: always
    networks:
      - pim
  mysql:
    image: mysql:5.7.29
    container_name: pim-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: im
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
        - pim
  redis:
    image: redis:6.0.6
    container_name: pim-redis
    ports:
      - "6379:6379"
    networks:
      - pim
  pim-server:
    build: ./
    container_name: pim-service-dev
    privileged: true
    ports:
      - 9501:9501
      - 9502:9502
    networks:
      - pim