version: '3'
networks:
      pim:
services:
  pim-web:
    image: jksusu/vue-im:0.04
    container_name: pim-web
    privileged: true
    ports:
      - "80:80"
    restart: always
    networks:
      - pim
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: im
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
        - pim
  redis:
    image: redis:6.0.6
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - pim
  pim-server:
    image: jksusu/hyperf-im:0.06
    container_name: pim-server
    privileged: true
    ports:
      - 9501:9501
      - 9502:9502
    networks:
      - pim